# Generated by Django 4.0.5 on 2022-07-30 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
